// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btvgneexjdghqrkszfjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0dmduZWV4amRnaHFya3N6ZmprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDgzNTgsImV4cCI6MjA3MzU4NDM1OH0.f-JXCytXokJNBn1jCBytcUTacAjSALpGgHs68p1w7gI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});